# Avalanche Historical Staking Distribution

### Setup

In [1]:
import datetime
import requests
import pandas as pd

In [2]:
# First date with any data
start_date = datetime.date(2020,9,23)

# Run until today
end_date = datetime.date.today()

### Getting Data

In [5]:
# inclusive for loop from start_date to end_date
rank = []
cumulative = []
for date in pd.date_range(start_date,end_date):
    
    # Doing this so we have something as a progress bar
    date_str = str(date.date())
    print(date_str)
    
    # pulled from: https://ava-labs-inc.metabaseapp.com/public/dashboard/249aea4f-6f83-45f4-8ed7-5cbdf9e9b026?single_date=2022-01-25
    # {data: {rows: [[ID, stake amount, rank], ...]}}
    rank_weight_url = f'https://ava-labs-inc.metabaseapp.com/api/public/dashboard/249aea4f-6f83-45f4-8ed7-5cbdf9e9b026/card/234?parameters=%5B%7B%22type%22%3A%22date%2Fsingle%22%2C%22value%22%3A%22{date_str}%22%2C%22target%22%3A%5B%22variable%22%2C%5B%22template-tag%22%2C%22FILTER_DATE%22%5D%5D%7D%5D'
    # {data: {rows: [[rank, weight], ...]}}
    cumulative_weight_url = f'https://ava-labs-inc.metabaseapp.com/api/public/dashboard/249aea4f-6f83-45f4-8ed7-5cbdf9e9b026/card/233?parameters=%5B%7B%22type%22%3A%22date%2Fsingle%22%2C%22value%22%3A%22{date_str}%22%2C%22target%22%3A%5B%22variable%22%2C%5B%22template-tag%22%2C%22FILTER_DATE%22%5D%5D%7D%5D'

    # get lists
    rank_weight_list = requests.get(rank_weight_url).json()['data']['rows']
    cumulative_weight_list = requests.get(cumulative_weight_url).json()['data']['rows']
    
    # stick on bigger lists
    rank.append({'date': date_str, 'rank': rank_weight_list})
    cumulative.append({'date': date_str, 'cumulative': cumulative_weight_list})

2020-09-23
2020-09-24
2020-09-25
2020-09-26
2020-09-27
2020-09-28
2020-09-29
2020-09-30
2020-10-01
2020-10-02
2020-10-03
2020-10-04
2020-10-05
2020-10-06
2020-10-07
2020-10-08
2020-10-09
2020-10-10
2020-10-11
2020-10-12
2020-10-13
2020-10-14
2020-10-15
2020-10-16
2020-10-17
2020-10-18
2020-10-19
2020-10-20
2020-10-21
2020-10-22
2020-10-23
2020-10-24
2020-10-25
2020-10-26
2020-10-27
2020-10-28
2020-10-29
2020-10-30
2020-10-31
2020-11-01
2020-11-02
2020-11-03
2020-11-04
2020-11-05
2020-11-06
2020-11-07
2020-11-08
2020-11-09
2020-11-10
2020-11-11
2020-11-12
2020-11-13
2020-11-14
2020-11-15
2020-11-16
2020-11-17
2020-11-18
2020-11-19
2020-11-20
2020-11-21
2020-11-22
2020-11-23
2020-11-24
2020-11-25
2020-11-26
2020-11-27
2020-11-28
2020-11-29
2020-11-30
2020-12-01
2020-12-02
2020-12-03
2020-12-04
2020-12-05
2020-12-06
2020-12-07
2020-12-08
2020-12-09
2020-12-10
2020-12-11
2020-12-12
2020-12-13
2020-12-14
2020-12-15
2020-12-16
2020-12-17
2020-12-18
2020-12-19
2020-12-20
2020-12-21
2020-12-22
2020-12-23
2020-12-24
2020-12-25
2020-12-26
2020-12-27
2020-12-28
2020-12-29
2020-12-30
2020-12-31
2021-01-01
2021-01-02
2021-01-03
2021-01-04
2021-01-05
2021-01-06
2021-01-07
2021-01-08
2021-01-09
2021-01-10
2021-01-11
2021-01-12
2021-01-13
2021-01-14
2021-01-15
2021-01-16
2021-01-17
2021-01-18
2021-01-19
2021-01-20
2021-01-21
2021-01-22
2021-01-23
2021-01-24
2021-01-25
2021-01-26
2021-01-27
2021-01-28
2021-01-29
2021-01-30
2021-01-31
2021-02-01
2021-02-02
2021-02-03
2021-02-04
2021-02-05
2021-02-06
2021-02-07
2021-02-08
2021-02-09
2021-02-10
2021-02-11
2021-02-12
2021-02-13
2021-02-14
2021-02-15
2021-02-16
2021-02-17
2021-02-18
2021-02-19
2021-02-20
2021-02-21
2021-02-22
2021-02-23
2021-02-24
2021-02-25
2021-02-26
2021-02-27
2021-02-28
2021-03-01
2021-03-02
2021-03-03
2021-03-04
2021-03-05
2021-03-06
2021-03-07
2021-03-08
2021-03-09
2021-03-10
2021-03-11
2021-03-12
2021-03-13
2021-03-14
2021-03-15
2021-03-16
2021-03-17
2021-03-18
2021-03-19
2021-03-20
2021-03-21
2021-03-22
2021-03-23
2021-03-24
2021-03-25
2021-03-26
2021-03-27
2021-03-28
2021-03-29
2021-03-30
2021-03-31
2021-04-01
2021-04-02
2021-04-03
2021-04-04
2021-04-05
2021-04-06
2021-04-07
2021-04-08
2021-04-09
2021-04-10
2021-04-11
2021-04-12
2021-04-13
2021-04-14
2021-04-15
2021-04-16
2021-04-17
2021-04-18
2021-04-19
2021-04-20
2021-04-21
2021-04-22
2021-04-23
2021-04-24
2021-04-25
2021-04-26
2021-04-27
2021-04-28
2021-04-29
2021-04-30
2021-05-01
2021-05-02
2021-05-03
2021-05-04
2021-05-05
2021-05-06
2021-05-07
2021-05-08
2021-05-09
2021-05-10
2021-05-11
2021-05-12
2021-05-13
2021-05-14
2021-05-15
2021-05-16
2021-05-17
2021-05-18
2021-05-19
2021-05-20
2021-05-21
2021-05-22
2021-05-23
2021-05-24
2021-05-25
2021-05-26
2021-05-27
2021-05-28
2021-05-29
2021-05-30
2021-05-31
2021-06-01
2021-06-02
2021-06-03
2021-06-04
2021-06-05
2021-06-06
2021-06-07
2021-06-08
2021-06-09
2021-06-10
2021-06-11
2021-06-12
2021-06-13
2021-06-14
2021-06-15
2021-06-16
2021-06-17
2021-06-18
2021-06-19
2021-06-20
2021-06-21
2021-06-22
2021-06-23
2021-06-24
2021-06-25
2021-06-26
2021-06-27
2021-06-28
2021-06-29
2021-06-30
2021-07-01
2021-07-02
2021-07-03
2021-07-04
2021-07-05
2021-07-06
2021-07-07
2021-07-08
2021-07-09
2021-07-10
2021-07-11
2021-07-12
2021-07-13
2021-07-14
2021-07-15
2021-07-16
2021-07-17
2021-07-18
2021-07-19
2021-07-20
2021-07-21
2021-07-22
2021-07-23
2021-07-24
2021-07-25
2021-07-26
2021-07-27
2021-07-28
2021-07-29
2021-07-30
2021-07-31
2021-08-01
2021-08-02
2021-08-03
2021-08-04
2021-08-05
2021-08-06
2021-08-07
2021-08-08
2021-08-09
2021-08-10
2021-08-11
2021-08-12
2021-08-13
2021-08-14
2021-08-15
2021-08-16
2021-08-17
2021-08-18
2021-08-19
2021-08-20
2021-08-21
2021-08-22
2021-08-23
2021-08-24
2021-08-25
2021-08-26
2021-08-27
2021-08-28
2021-08-29
2021-08-30
2021-08-31
2021-09-01
2021-09-02
2021-09-03
2021-09-04
2021-09-05
2021-09-06
2021-09-07
2021-09-08
2021-09-09
2021-09-10
2021-09-11
2021-09-12
2021-09-13
2021-09-14
2021-09-15
2021-09-16
2021-09-17
2021-09-18
2021-09-19
2021-09-20
2021-09-21
2021-09-22
2021-09-23
2021-09-24
2021-09-25
2021-09-26
2021-09-27
2021-09-28
2021-09-29
2021-09-30
2021-10-01
2021-10-02
2021-10-03
2021-10-04
2021-10-05
2021-10-06
2021-10-07
2021-10-08
2021-10-09
2021-10-10
2021-10-11
2021-10-12
2021-10-13
2021-10-14
2021-10-15
2021-10-16
2021-10-17
2021-10-18
2021-10-19
2021-10-20
2021-10-21
2021-10-22
2021-10-23
2021-10-24
2021-10-25
2021-10-26
2021-10-27
2021-10-28
2021-10-29
2021-10-30
2021-10-31
2021-11-01
2021-11-02
2021-11-03
2021-11-04
2021-11-05
2021-11-06
2021-11-07
2021-11-08
2021-11-09
2021-11-10
2021-11-11
2021-11-12
2021-11-13
2021-11-14
2021-11-15
2021-11-16
2021-11-17
2021-11-18
2021-11-19
2021-11-20
2021-11-21
2021-11-22
2021-11-23
2021-11-24
2021-11-25
2021-11-26
2021-11-27
2021-11-28
2021-11-29
2021-11-30
2021-12-01
2021-12-02
2021-12-03
2021-12-04
2021-12-05
2021-12-06
2021-12-07
2021-12-08
2021-12-09
2021-12-10
2021-12-11
2021-12-12
2021-12-13
2021-12-14
2021-12-15
2021-12-16
2021-12-17
2021-12-18
2021-12-19
2021-12-20
2021-12-21
2021-12-22
2021-12-23
2021-12-24
2021-12-25
2021-12-26
2021-12-27
2021-12-28
2021-12-29
2021-12-30
2021-12-31
2022-01-01
2022-01-02
2022-01-03
2022-01-04
2022-01-05
2022-01-06
2022-01-07
2022-01-08
2022-01-09
2022-01-10
2022-01-11
2022-01-12
2022-01-13
2022-01-14
2022-01-15
2022-01-16
2022-01-17
2022-01-18
2022-01-19
2022-01-20
2022-01-21
2022-01-22
2022-01-23
2022-01-24
2022-01-25

### Clean up data

In [7]:
rank_df = pd.DataFrame(rank)
cumulative_df = pd.DataFrame(cumulative)

In [9]:
cumulative_df

           date                                         cumulative
0    2020-09-23  [[1, 0.09179796638094224], [2, 0.1789408852731...
1    2020-09-24  [[1, 0.0705515181776062], [2, 0.14110303635521...
2    2020-09-25  [[1, 0.06418845583470877], [2, 0.1283769116694...
3    2020-09-26  [[1, 0.05044181707656916], [2, 0.1008836341531...
4    2020-09-27  [[1, 0.04813200586552204], [2, 0.0962640117310...
..          ...                                                ...
485  2022-01-21  [[1, 0.012623944962451486], [2, 0.025247889924...
486  2022-01-22  [[1, 0.012634852948199132], [2, 0.025269705896...
487  2022-01-23  [[1, 0.012623280435964317], [2, 0.025246560871...
488  2022-01-24  [[1, 0.0126207879973492], [2, 0.02524157599469...
489  2022-01-25  [[1, 0.012610704542457413], [2, 0.025221409084...

[490 rows x 2 columns]

### Nakamoto Coefficient

In [12]:
dict_list = []
for index, row in cumulative_df.iterrows():
    date = row['date']
    cumulative_list = row['cumulative']
    total_validators = len(cumulative_list)
    
    count = 0
    total_share = cumulative_list[count][1]
    while total_share < 0.333:
        count+=1
        total_share = cumulative_list[count][1]
    
    one_third = cumulative_list[count][0]
    
    
    nakamoto_coeff = one_third / total_validators
    
    entry = {'date': date, 'nakmoto': nakamoto_coeff, 'one_third': one_third, 'validators': total_validators}
    dict_list.append(entry)

In [17]:
nakamoto_df = pd.DataFrame(dict_list)
nakamoto_df.set_index('date', inplace=True)
nakamoto_df.to_csv('avalanche_nakamoto.csv')
nakamoto_df

             nakmoto  one_third  validators
date
2020-09-23  0.022831          5         219
2020-09-24  0.017483          5         286
2020-09-25  0.018576          6         323
2020-09-26  0.019499          7         359
2020-09-27  0.018182          7         385
...              ...        ...         ...
2022-01-21  0.022005         27        1227
2022-01-22  0.021792         27        1239
2022-01-23  0.021916         27        1232
2022-01-24  0.021774         27        1240
2022-01-25  0.021827         27        1237

[490 rows x 3 columns]